# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shellsort_pb2 as shellsort__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in shellsort_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShellSortServiceStub(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeInitialData = channel.unary_unary(
                '/shellsort.ShellSortService/InitializeInitialData',
                request_serializer=shellsort__pb2.InitialDataRequest.SerializeToString,
                response_deserializer=shellsort__pb2.InitialDataResponse.FromString,
                _registered_method=True)
        self.UploadInitialDataBatch = channel.unary_unary(
                '/shellsort.ShellSortService/UploadInitialDataBatch',
                request_serializer=shellsort__pb2.InitialDataBatchRequest.SerializeToString,
                response_deserializer=shellsort__pb2.InitialDataBatchResponse.FromString,
                _registered_method=True)
        self.FinalizeInitialData = channel.unary_unary(
                '/shellsort.ShellSortService/FinalizeInitialData',
                request_serializer=shellsort__pb2.FinalizeInitialDataRequest.SerializeToString,
                response_deserializer=shellsort__pb2.FinalizeInitialDataResponse.FromString,
                _registered_method=True)
        self.ReadAbElement = channel.unary_unary(
                '/shellsort.ShellSortService/ReadAbElement',
                request_serializer=shellsort__pb2.ReadAbElementRequest.SerializeToString,
                response_deserializer=shellsort__pb2.ReadAbElementResponse.FromString,
                _registered_method=True)
        self.InitializeHashArray = channel.unary_unary(
                '/shellsort.ShellSortService/InitializeHashArray',
                request_serializer=shellsort__pb2.InitializeHashArrayRequest.SerializeToString,
                response_deserializer=shellsort__pb2.InitializeHashArrayResponse.FromString,
                _registered_method=True)
        self.SendHashValue = channel.unary_unary(
                '/shellsort.ShellSortService/SendHashValue',
                request_serializer=shellsort__pb2.SendHashValueRequest.SerializeToString,
                response_deserializer=shellsort__pb2.SendHashValueResponse.FromString,
                _registered_method=True)
        self.FinalizeHashArray = channel.unary_unary(
                '/shellsort.ShellSortService/FinalizeHashArray',
                request_serializer=shellsort__pb2.FinalizeHashArrayRequest.SerializeToString,
                response_deserializer=shellsort__pb2.FinalizeHashArrayResponse.FromString,
                _registered_method=True)
        self.UseHashArrayForSorting = channel.unary_unary(
                '/shellsort.ShellSortService/UseHashArrayForSorting',
                request_serializer=shellsort__pb2.UseHashArrayForSortingRequest.SerializeToString,
                response_deserializer=shellsort__pb2.UseHashArrayForSortingResponse.FromString,
                _registered_method=True)
        self.Initialize = channel.unary_unary(
                '/shellsort.ShellSortService/Initialize',
                request_serializer=shellsort__pb2.InitRequest.SerializeToString,
                response_deserializer=shellsort__pb2.InitResponse.FromString,
                _registered_method=True)
        self.GetPair = channel.unary_unary(
                '/shellsort.ShellSortService/GetPair',
                request_serializer=shellsort__pb2.GetPairRequest.SerializeToString,
                response_deserializer=shellsort__pb2.GetPairResponse.FromString,
                _registered_method=True)
        self.WritePair = channel.unary_unary(
                '/shellsort.ShellSortService/WritePair',
                request_serializer=shellsort__pb2.WritePairRequest.SerializeToString,
                response_deserializer=shellsort__pb2.WritePairResponse.FromString,
                _registered_method=True)
        self.GetMate = channel.unary_unary(
                '/shellsort.ShellSortService/GetMate',
                request_serializer=shellsort__pb2.MateRequest.SerializeToString,
                response_deserializer=shellsort__pb2.MateResponse.FromString,
                _registered_method=True)
        self.GetFinalArray = channel.unary_unary(
                '/shellsort.ShellSortService/GetFinalArray',
                request_serializer=shellsort__pb2.FinalArrayRequest.SerializeToString,
                response_deserializer=shellsort__pb2.FinalArrayResponse.FromString,
                _registered_method=True)


class ShellSortServiceServicer(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    def InitializeInitialData(self, request, context):
        """Phase 0: Element Storage
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadInitialDataBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeInitialData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadAbElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeHashArray(self, request, context):
        """Phase 1: Hash Array Streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHashValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalizeHashArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UseHashArrayForSorting(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """Phase 2: Randomized Shell Sort
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WritePair(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFinalArray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShellSortServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeInitialData': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeInitialData,
                    request_deserializer=shellsort__pb2.InitialDataRequest.FromString,
                    response_serializer=shellsort__pb2.InitialDataResponse.SerializeToString,
            ),
            'UploadInitialDataBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadInitialDataBatch,
                    request_deserializer=shellsort__pb2.InitialDataBatchRequest.FromString,
                    response_serializer=shellsort__pb2.InitialDataBatchResponse.SerializeToString,
            ),
            'FinalizeInitialData': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeInitialData,
                    request_deserializer=shellsort__pb2.FinalizeInitialDataRequest.FromString,
                    response_serializer=shellsort__pb2.FinalizeInitialDataResponse.SerializeToString,
            ),
            'ReadAbElement': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadAbElement,
                    request_deserializer=shellsort__pb2.ReadAbElementRequest.FromString,
                    response_serializer=shellsort__pb2.ReadAbElementResponse.SerializeToString,
            ),
            'InitializeHashArray': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeHashArray,
                    request_deserializer=shellsort__pb2.InitializeHashArrayRequest.FromString,
                    response_serializer=shellsort__pb2.InitializeHashArrayResponse.SerializeToString,
            ),
            'SendHashValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHashValue,
                    request_deserializer=shellsort__pb2.SendHashValueRequest.FromString,
                    response_serializer=shellsort__pb2.SendHashValueResponse.SerializeToString,
            ),
            'FinalizeHashArray': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalizeHashArray,
                    request_deserializer=shellsort__pb2.FinalizeHashArrayRequest.FromString,
                    response_serializer=shellsort__pb2.FinalizeHashArrayResponse.SerializeToString,
            ),
            'UseHashArrayForSorting': grpc.unary_unary_rpc_method_handler(
                    servicer.UseHashArrayForSorting,
                    request_deserializer=shellsort__pb2.UseHashArrayForSortingRequest.FromString,
                    response_serializer=shellsort__pb2.UseHashArrayForSortingResponse.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=shellsort__pb2.InitRequest.FromString,
                    response_serializer=shellsort__pb2.InitResponse.SerializeToString,
            ),
            'GetPair': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPair,
                    request_deserializer=shellsort__pb2.GetPairRequest.FromString,
                    response_serializer=shellsort__pb2.GetPairResponse.SerializeToString,
            ),
            'WritePair': grpc.unary_unary_rpc_method_handler(
                    servicer.WritePair,
                    request_deserializer=shellsort__pb2.WritePairRequest.FromString,
                    response_serializer=shellsort__pb2.WritePairResponse.SerializeToString,
            ),
            'GetMate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMate,
                    request_deserializer=shellsort__pb2.MateRequest.FromString,
                    response_serializer=shellsort__pb2.MateResponse.SerializeToString,
            ),
            'GetFinalArray': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFinalArray,
                    request_deserializer=shellsort__pb2.FinalArrayRequest.FromString,
                    response_serializer=shellsort__pb2.FinalArrayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shellsort.ShellSortService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shellsort.ShellSortService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShellSortService(object):
    """============================================================================
    SERVICE DEFINITION
    ============================================================================

    """

    @staticmethod
    def InitializeInitialData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/InitializeInitialData',
            shellsort__pb2.InitialDataRequest.SerializeToString,
            shellsort__pb2.InitialDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadInitialDataBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/UploadInitialDataBatch',
            shellsort__pb2.InitialDataBatchRequest.SerializeToString,
            shellsort__pb2.InitialDataBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeInitialData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/FinalizeInitialData',
            shellsort__pb2.FinalizeInitialDataRequest.SerializeToString,
            shellsort__pb2.FinalizeInitialDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadAbElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/ReadAbElement',
            shellsort__pb2.ReadAbElementRequest.SerializeToString,
            shellsort__pb2.ReadAbElementResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeHashArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/InitializeHashArray',
            shellsort__pb2.InitializeHashArrayRequest.SerializeToString,
            shellsort__pb2.InitializeHashArrayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHashValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/SendHashValue',
            shellsort__pb2.SendHashValueRequest.SerializeToString,
            shellsort__pb2.SendHashValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalizeHashArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/FinalizeHashArray',
            shellsort__pb2.FinalizeHashArrayRequest.SerializeToString,
            shellsort__pb2.FinalizeHashArrayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UseHashArrayForSorting(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/UseHashArrayForSorting',
            shellsort__pb2.UseHashArrayForSortingRequest.SerializeToString,
            shellsort__pb2.UseHashArrayForSortingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/Initialize',
            shellsort__pb2.InitRequest.SerializeToString,
            shellsort__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/GetPair',
            shellsort__pb2.GetPairRequest.SerializeToString,
            shellsort__pb2.GetPairResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WritePair(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/WritePair',
            shellsort__pb2.WritePairRequest.SerializeToString,
            shellsort__pb2.WritePairResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/GetMate',
            shellsort__pb2.MateRequest.SerializeToString,
            shellsort__pb2.MateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFinalArray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shellsort.ShellSortService/GetFinalArray',
            shellsort__pb2.FinalArrayRequest.SerializeToString,
            shellsort__pb2.FinalArrayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
